/**
 * Available flag codes
 * This file is auto-generated by scripts/generate-flags.ts
 * Do not edit manually - run 'npm run generate-flags' to regenerate
 */

export const AVAILABLE_FLAG_CODES = new Set<string>([
    'AR',
    'AU',
    'BO',
    'BR',
    'CA',
    'CAT',
    'CL',
    'CO',
    'CR',
    'CU',
    'DE',
    'DO',
    'EC',
    'ES',
    'EUS',
    'FR',
    'GAL',
    'GB',
    'GT',
    'HN',
    'IT',
    'MX',
    'NI',
    'NZ',
    'PA',
    'PE',
    'PR',
    'PT',
    'PY',
    'SV',
    'US',
    'UY',
    'VE'
]);

/**
 * Get available flag codes as an array (sorted)
 */
export function getAvailableFlagCodes(): string[] {
  return Array.from(AVAILABLE_FLAG_CODES).sort();
}
