/**
 * Generate flags constants from public/icons/flags directory
 * This script runs during build to create a static list of available flags
 * that can be used in serverless environments like Vercel
 */

import { readdir } from 'fs/promises';
import { join } from 'path';
import { writeFile } from 'fs/promises';

const FLAGS_DIR = join(process.cwd(), 'public', 'icons', 'flags');
const OUTPUT_FILE = join(process.cwd(), 'constants', 'availableFlags.ts');

async function generateFlagsConstants() {
  try {
    console.log('[generate-flags] Reading flags from:', FLAGS_DIR);
    const files = await readdir(FLAGS_DIR);
    const flags = new Set<string>();

    files.forEach((file) => {
      if (file.endsWith('.svg')) {
        const code = file.replace('.svg', '').toUpperCase();
        flags.add(code);
      }
    });

    const flagsArray = Array.from(flags).sort();
    const flagsSetString = flagsArray
      .map((flag) => `    '${flag}'`)
      .join(',\n');

    const content = `/**
 * Available flag codes
 * This file is auto-generated by scripts/generate-flags.ts
 * Do not edit manually - run 'npm run generate-flags' to regenerate
 */

export const AVAILABLE_FLAG_CODES = new Set<string>([
${flagsSetString}
]);

/**
 * Get available flag codes as an array (sorted)
 */
export function getAvailableFlagCodes(): string[] {
  return Array.from(AVAILABLE_FLAG_CODES).sort();
}
`;

    await writeFile(OUTPUT_FILE, content, 'utf-8');
    console.log('[generate-flags] Generated flags constants:', {
      count: flags.size,
      outputFile: OUTPUT_FILE,
      flags: flagsArray,
    });
  } catch (error) {
    console.error('[generate-flags] Error generating flags constants:', error);
    process.exit(1);
  }
}

generateFlagsConstants();
